default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: deploy
  password: pointer
development:
  <<: *default
  database: cooler_development
test:
  <<: *default
  database: cooler_test
production:
  <<: *default
  database: cooler_production
